# Generated by Django 3.2.8 on 2022-06-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_post_fetured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fetured_image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
    ]
